name: CI for Next.js
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./Modu_expense_book/modu_expend_book # 작업 디렉토리 기본값 설정
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ./Modu_expense_book/modu_expend_book/node_modules # 캐시 경로 수정
        key: ${{ runner.os }}-node-${{ hashFiles('Modu_expense_book/modu_expend_book/package-lock.json') }} # 경로 수정
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19.0'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test
      
    - name: Build Next.js app
      run: npm run build
